
export enum LeaderboardRuleType {
    GAMES_WON = "GAMES_WON",
    RAKE_GENERATED="RAKE_GENERATED",
    TOTAL_GAMES = "TOTAL_GAMES",
    DEPOSIT_AMOUNT = "DEPOSIT_AMOUNT",
    LOSING_STREAK = "LOSING_STREAK",
    HIGHEST_SCORE= "HIGHEST_SCORE",
    ENTRY_FEE = "ENTRY_FEE",
    DANGAL_POINTS = "DANGAL_POINTS"
  }
