
export enum DocumentStatus {
  SELECT = "--SELECT--",
  INITIATED="INITIATED",
  APPROVED = "APPROVED",
  INVALID_DOCUMENT = "INVALID DOCUMENT",
  INVALID_IMAGE = "INVALID IMAGE",
  INVALID_USER = "INVALID USER",
  SERVER_ERROR = "SERVER_ERROR",
  INVALID_IMAGE_SIZE="INVALID IMAGE SIZE",
  PROFILE_MISMATCH = "PROFILE MISMATCH",
  INVALID_REQUEST = "INVALID REQUEST",
  INVALID_AADHAR = "INVALID AADHAR",
  DUPLICATE_DOCUMENT = "DUPLICATE DOCUMENT"
  }
