
export enum GeoRestrictionAllGames {
  CALLBREAK = "CALLBREAK",
  POKER = "POKER",
  RUMMY = "RUMMY",
  POOL = "POOL",
  FRUIT_SPLIT = "FRUIT_SPLIT",
  RUNNER_NUMBER_ONE = "RUNNER_NUMBER_ONE",
  BUBBLE_SHOOTER = "BUBBLE_SHOOTER",
  KNIFE_CUT = "KNIFE_HIT",
  ARCHERY = "ARCHERY",
  CARROM = "CARROM",
  CANDY_CRUSH = "CANDY_CRUSH",
  LUDO = "LUDO",
  FANTASY = "FANTASY",
  STREET_RACER = "STREET_RACER"
}
