
export enum WithdrawalStatus {
    INITIATED = "INITIATED",
    FULFILLED="FULFILLED",
    FAILED = "FAILED",
    CANCELLED = "CANCELLED",
    PENDING = "PENDING",
    DECLINED= "DECLINED",
    REJECTED = "REJECTED",
    IN_PROGRESS="IN_PROGRESS",
    REVERSED = "REVERSED"
  }


